checks:
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
exclude_patterns:
- "server/migrations/"
- "server/middlewares"
- "server/models"
- "server/tests"
- "tests/"
- "spec/"