version: "2"
checks:
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
exclude_patterns:
- "server/migrations/"
- "server/middlewares"
- "server/models"
- "server/tests"
- "tests/"
- "spec/"