language: node_js

node_js:
  - node
  - "6"

script: 
 - npm run test

after_script: 
 - npm run coverage
 - npm install codeclimate-test-reporter
 - codeclimate-test-reporter < ./coverage/lcov.info
